// pages/index.tsx

import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import { Header, WelcomePage, Gallery } from '@/components'


export default function Home() {
  return (
    <>
      <Head>
        <title>owo - Économie circulaire à Québec</title>
        <meta name="description" content="Generated by create next app" />

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="owo" />
        <link rel="apple-touch-icon" href="/favicon.png" />

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />

        <link rel="manifest" href="manifest.json"></link>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Container fluid className="bg-primary vh-100">
        <Header />
        <WelcomePage />
      </Container>
    </>
  )
}
